### ISSUE TITLE
Please help me with it

### ISSUE THREAD

**Issue by raypixell** [RajeshSivadasan/alice_blue#2]
i am getting this error. please help me

2021-10-04 09:52:40.426895|1|Initialising D:\Python\alice_blue-main\ab.py
2021-10-04 09:52:40.883586|1|Setting up initial sleep time of 2 seconds.
Traceback (most recent call last):
  File "C:\Users\home\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 789, in get
    value = d[option]
  File "C:\Users\home\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\home\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'nifty_no_trade_zones'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\alice_blue-main\ab.py", line 236, in <module>
    nifty_no_trade_zones = eval(cfg.get("info", "nifty_no_trade_zones"))
  File "C:\Users\home\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'nifty_no_trade_zones' in section: 'info'

**Comment by RajeshSivadasan** [comment]
Sorry, there were some additional parameters implemented which was not in the .ini file. This error has come as the mentioned parameter (nifty_no_trade_zones) was not present in the ab.ini file. I have updated the latest ab.ini file. Please feel free to modify the parameters as per your needs.
